### ISSUE TITLE
Themes are only being build if library project contains a .library file

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-builder#110]
## Expected Behavior
`CSS` files should be build regardless of `.library` file existence

## Current Behavior
`CSS` files are only being build if library project contains a `.library` file

## Steps to reproduce the issue
1. Clone ui5lab sample library
` git clone https://github.com/UI5Lab/UI5Lab-library-simple`

2. Delete `.library` file
` rm src/ui5lab/geometry/.library`

3. Build library
` ui5 build`

3. Check themes folder in `dist` - css files have no been generated
```shell
$ ls ./dist/resources/ui5lab/geometry/themes/base/
Circle.less  library.source.less  Square.less  Triangle.less
```

## Affected components
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by srenwickblum** [comment]
It looks like this issue has crept back again. We're not used to using these .library files, I believe they're only used internally in SAP. 

Attached is my super simple example, to reproduce this issue:
1. Unzip,
2, within com.test.mylib, call "npm link"
3. within the theme lib: 
    - npm update, 
    - npm link com.test.mylib
    - ui5 build --all

This should build the theme which supports sap.ui.core and com.test.mylib.. however
Look in ./dest/resource/sap/ui/core/themes/mytheme, all the correct generated css aritfacts are present. 
Now look in:
./dest/resource/com/test/mylib/themes/mytheme, the less artificats were copied over, but nothing else.

[temp.zip](https://github.com/SAP/ui5-builder/files/2851638/temp.zip)

Please note I have included the .library file, simply renamed to .___library. This makes it easier (faster) to compare a build with and without this .library file.

**Comment by srenwickblum** [comment]
@RandomByte would you prefer open a new issue for this? I can't reopen this issue because I didn't create it. 
@BenReim are you able to check if this still works as expected for you?

**Comment by RandomByte** [comment]
Reopening. We'll look into it asap

**Comment by RandomByte** [comment]
@matz3 could you have a look?

**Comment by srenwickblum** [comment]
I feel I must point out, this is no blocker for us. I simply fabricated my own .library and everything works now. When I saw this ticket, it was clear this wasn't the desired behaviour so I felt someone might want to know.

**Comment by RandomByte** [comment]
fyi @stopcoder

**Comment by cschuff** [comment]
Also the .library file has to include the right dependencies.

I had the following failure (with `@ui5/cli@1.5.5`):
```
> ui5 serve -p 3000

WARN types:library:LibraryFormatter Failed to detect namespace or namespace is empty for project themelib_sap_belize. Check verbose log for details.
Server started
URL: http://localhost:3000
TypeError: Cannot read property 'length' of undefined
    at selectorEquals (/.../node_modules/@ui5/cli/node_modules/less-openui5/lib/diff.js:23:23)
    at Diffing.diffRules (/.../node_modules/@ui5/cli/node_modules/less-openui5/lib/diff.js:83:12)
    at Diffing.run (/.../node_modules/@ui5/cli/node_modules/less-openui5/lib/diff.js:140:37)
    at diff (/.../node_modules/@ui5/cli/node_modules/less-openui5/lib/diff.js:150:38)
    at applyScope (/.../node_modules/@ui5/cli/node_modules/less-openui5/lib/index.js:313:17)
    at /.../node_modules/@ui5/cli/node_modules/less-openui5/lib/index.js:344:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I added
```
  <dependency>
    <libraryName>themelib_sap_belize</libraryName>
  </dependency>
```
to .library and it works all fine again.

BR
Chris

**Comment by matz3** [comment]
Sorry for the late update.
The dependencies for the build-time should actually be taken from the project (package.json / ui5.yaml).
So we would need some more information here, in case this is still relevant.
