### ISSUE TITLE
neo-app.json file is not part of build result

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-builder#114]
## Expected Behavior
If a `neo-app.json` file exists, it should be included in the build result. This should be true for both library and application projects. 

## Current Behavior
Currently, the `neo-app.json` file is not included in the build result. Therefore, destinations within a [SAP Cloud Platform account (NEO environment) / WebIDE](https://openui5nightly.hana.ondemand.com/#/topic/28fa7538c67e4280a0b7708de2951278) will not be set up as expected. 

## Affected components *(if known)*
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
Thanks for reporting! As the `neo-app.json` is not a UI5 runtime resource (thus also not located in the `webapp` or `src` directory of a UI5 project) it is *currently* out of scope to handle this file in the UI5 Tooling.

This might change *if* the tooling would gain an understanding of this file. Or if there is greater demand in adding this. This also depends on the outcome of https://github.com/SAP/ui5-tooling/pull/41

**There are several workarounds available:**
- Copy the file manually or scripted using UNIX command `cp` or similar
- Add a custom task which reads the file and generates a UI5 Resource in the projects workspace: https://github.com/SAP/ui5-project/blob/master/docs/BuildExtensibility.md#custom-task-extension

I'll close this as wontfix for the time being.
