### ISSUE TITLE
ui5 build creates Component.preload in old format

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-builder#157]
## Expected Behavior
ui5 build preload creates a Component-preload.js in the new format (the one using sap.ui...)

## Current Behavior
ui5 build preload creates a Component-preload.js in the *old* format (the one using jQuery.sap...)

## Context
I guess this is more of a consulting case, sorry; I seem to be doing something wrong.

I am using UI5 1.61.2 in my application and have the UI5 dependencies installed in node_modules. There does not seem to be a parameter for old vs. new format, so something must be triggering this. What are the prerequisites for getting the new format?

**Comment by codeworrior** [comment]
I'm a bit confused. According to the long text, you expect the old format, but get the new format? But the subject of the issue complains about the opposite: getting the old format?

Just in case that "Expected" and "Current" have been accidentally swapped: trigger for the new format is the existence of a module "ui5loader.js" in the resources of the application.  Does your application have a dependency to sap.ui.core?

**Comment by winterkind** [comment]
Yep, they were swapped - I changed the text. Thanks for your patience.

Yes, sap.ui.core is a dependency in package.json and in manifest.json. The npm packages are installed in node_modules. So would I have to map the resources path to node_modules?

**Comment by RandomByte** [comment]
> [...] the new format (the one using jQuery.sap...) [...]
> [...] the *old* format (the one using sap.ui...) [...]

Could you please check your text again? I guess the **new** format is the one using **sap.ui.\*** APIs.

Just to make sure we're on the same page.

**Comment by winterkind** [comment]
Your are right, I messed up those two simple lines :( 

Tooling version is 1.0.0.

I think in the meantime I realized that the place where the builder looks for `ui5loader.js` is in the build result: `dist/resources`. However, that folder is empty except for a `sap-ui-version.js` and two pictures 
from my source folder of the same name. Maybe my project structure is the problem? Here it is:

```
root/  <- This is where I have my ui5.yaml (plus package.json etc.)
  src/  <- My "real" source folder
  webapp/  <- The Babel-transpiled version of my source folder. Same content plus source maps. This is where I want to build my preload from.
    index.html  <- The index.html for my app
    ea/
      solcat/  <- Folder containing my app's component
        ...
        resources/  <- Folder containing two pictures
        ...
        Component.js
        manifest.json
        ...
```
My ui5.yaml looks like this:
```
specVersion: "1.0"
type: application
metadata:
  name: "easolutioncatalog"
resources:
  configuration:
    paths:
      "webapp": "./webapp/ea/solcat/"
```
After `ui5 build -a` or `ui5 build preload` I get a `dist` folder that has all files and folders from `webapp/ea/solcat/`. But `dist/resources` only contains the three before-mentioned files. Maybe my project should not have a folder called `resources`?

**Comment by RandomByte** [comment]
Can you give us the output of `ui5 tree`? I'm interested whether your projects dependency tree actually contains the "sap.ui.core" project.

**Comment by RandomByte** [comment]
Hm, seems like no dependencies have been detected for this project. Is `@openui5/sap.ui.core` listed in the `dependencies` object inside your `package.json`?

**Comment by winterkind** [comment]
That was the missing hint. `sap.ui.core` was in `package.json` but in the `devDependencies`. So those are apparently not checked.

After I moved them to `dependencies`, the the build works. I need to do at least one `ui5 build --all`, after that `ui5 build` is enough to get a preload in the new format.

One verification maybe: the UI5 build in `resources/` contains all controls of the libraries I have in `package.json`, not only those my app uses. That is intended, correct?

**Comment by RandomByte** [comment]
Glad to hear that 👍 

> One verification maybe: the UI5 build in resources/ contains all controls of the libraries I have in package.json, not only those my app uses. That is intended, correct?

Yes. There can be cases where we do not correctly identify a control dependency of your app (e.g. because of dynamic require calls). Therefore we still want to have all controls available as a fallback.

If you have further *questions*, please feel free to join us in the `#tooling` channel of the [OpenUI5 Slack](https://join-ui5-slack.herokuapp.com/)!

**Comment by matz3** [comment]
@RandomByte @codeworrior do you think it makes sense to
- Log something in case we can't detect the format
- and/or use the new format as default and fallback to the old one in case no `ui5loader.js` is present?

We could even consider using a different hint such as the `sap.ui5/dependencies/minUI5Version` entry from `manifest.json` for use cases where no local dependencies are present.

Just thinking about how we could prevent someone from running into this again, as it's not straight-forward to find the root cause.
