### ISSUE TITLE
Explain how self-contained build can be split in multiple parts

### ISSUE THREAD

**Issue by gregorwolf** [SAP/ui5-builder#163]
## Expected Behavior
It seems to be possible to control the number of parts of a bundle via the parameter numberOfParts in the bundleOptions section of a bundleDefinition. It should be documented how to use this option for a self-contained build.

My target is to bundle OpenUI5 for an app that should run standalone on an ESP8266 / ESP32 as @jpenninkhof did it already in 206 with his own script: [Minimising UI5 app’s footprint to run from an ESP8266](https://blogs.sap.com/2016/04/01/minimizing-ui5-app-s-footprint-to-run-from-an-esp8266/). Now I would like to use the UI5-tooling. The challenge is that it seems that the ESP8266 has issues serving files larger than 400 kByte. My current self-contained build results in a sap-ui-custom.js with 2010063 Byte. When I gzip this I get down to 633808 Byte. But that is not enough. So I hope to get some hints how I can split the self-contained build in multiple parts.

## Current Behavior
There is no documentation that I've found regarding the bundles section for the ui5.yaml in [Configuration](https://github.com/SAP/ui5-project/blob/master/docs/Configuration.md).

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.0.0`

## Affected components *(if known)*
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by gregorwolf** [comment]
Thank you @matz3 for the nice example. Is there a way I can bring down the build result to what `ui5 build self-contained` does? With the `npm run-script build` a `ui5 build --a` is started that does not only create the sap-ui-custom-0.js and sap-ui-custom-1.js but also all the debug sources.

**Comment by RandomByte** [comment]
> With the `npm run-script` build a `ui5 build --a` is started that does not only create the sap-ui-custom-0.js and sap-ui-custom-1.js but also all the debug sources

This is intended as you may need the debug sources when debugging your application (`?sap-ui-debug=true`). You can use `--exclude-task=createDebugFiles` if you really don't like them.

**Comment by gregorwolf** [comment]
To make communication easier I've put my repository to [IASServoRemote](https://github.com/gregorwolf/IASServoRemote). The goal is to have a self-contained OpenUI5 that together with the app is:

- less than 1MB (Size of the Flash Memory in my ESP8266)
- that no file is bigger than 400 KB (Maximum the ESP8266 can deliver in one HTTP request.

I've reached this goal with the current build process I'm down to 596K. And the sap-ui-custom files are 278K and 263K. But I get now this error in the console when starting the app from the ESP8266 webserver:

`Uncaught Error: failed to load 'sap/m/Shell.js' from res/sap/m/Shell.js: 404 - Not Found`

**Comment by codeworrior** [comment]
The self-contained build only analyzes *.js files, not *.html files. Your index.html contains a small code block that uses "sap.m.Shell". As it is not analyzed, that dependency is not found and therefore not packaged.

We currently say 'good bye' to inline scripts in our samples to improve their CSP compliance. Maybe you could do the same? Alternatively, you can explicitely list sap/m/Shell in the bundle configuration in the ui5.yaml (in the "preload" section, just after "sap/ui/core/Core".

BTW: the self contained build packages all dependencies, even conditional dependencies. This for example includes the support tooling or the technical info by default. If you want, you can add another pattern to the same preload section, omitting "!sap/ui/core/support/".

**Comment by gregorwolf** [comment]
Thank you for the tip regarding the inline script. I've removed that now, but even with my definition of sap/ui/core/ComponentSupport in the Component.js I get this error:

`Error: failed to load 'sap/ui/core/ComponentSupport.js' from res/sap/ui/core/ComponentSupport.js`

**Comment by codeworrior** [comment]
Strange. I cloned your repo, did a `ui5 build --a` and could start the `index-multiple-parts.htm` (only the Servo was not accessible - surprise, surprise :-). 

The only thing that I struggled with was serving the dist folder and renaming `resources` to `res`. As it worked with a static-server, I would assume there must be something with your server setup (or caching?). 

Or can I somehow create a context closer to yours?

**Comment by gregorwolf** [comment]
I've created http://servo.computerservice-wolf.com/ which is a hosted version of what I deploy to the ESP8266. I serve there the content of the data folder that is created when running the current version of the build.sh script. This is my apache2 virtual host config file:

```
<VirtualHost *:80>
  ServerAdmin webmaster@computerservice-wolf.com
  DocumentRoot /home/gwolf/public_html/IASServoRemote/data
  ServerName servo.computerservice-wolf.com
  ServerAlias servo.computerservice-wolf.com

  Options +MultiViews
  RemoveType .gz
  AddEncoding gzip .gz
  <FilesMatch ".+\.tar\.gz$">
    RemoveEncoding .gz
    # Note:  Can use application/x-gzip for backwards-compatibility
    AddType application/gzip .gz
  </FilesMatch>

  <Directory "/home/gwolf/public_html/IASServoRemote/data">
        Options Indexes FollowSymlinks MultiViews
        AllowOverride None
        Order allow,deny
        Allow from all
  </Directory>
</VirtualHost>
```
It seems that the css files for the theming are not loaded from the pre-packaged sap-ui-custom files. Instead they are tried to get loaded directly. Unfortunately that would also be an issue on the ESP8266 as the maximum path length is 32 characters.

**Comment by RandomByte** [comment]
Unfortunately, the UI5 Tooling cannot bundle themes yet: https://github.com/SAP/ui5-builder/issues/91

Have you been able to resolve the [`failed to load 'sap/ui/core/ComponentSupport.js'`](https://github.com/SAP/ui5-builder/issues/163#issuecomment-459792829) error?

**Comment by matz3** [comment]
The `numberOfParts` configuration has been documented in the meanwhile: https://sap.github.io/ui5-tooling/pages/Configuration/#properties

For the missing ComponentSupport, see https://github.com/SAP/ui5-builder/issues/92

Therefore closing this issue.
