### ISSUE TITLE
debug mode is causing an infinite loop

### ISSUE THREAD

**Issue by srenwickblum** [SAP/ui5-builder#175]
## Expected Behavior
When I enter the url parameter ?sap-ui-debug=true page reloads using the *-dbg.js files in place of the *-preload.js

## Current Behavior
sap-ui-core.js loads sap-ui-core-dbg.js (as expected) but then sap-ui-core-dbg.js calls for itself to be loaded (again) and so on...
**Note:** this doesn't happen when using ``ui5 serve``, only when using a normal http server. Encountered this using WebSphere, so tried it using a simple (as possible) NodeJS http server - same results.

## Steps to reproduce the issue
1. clone [openui5-sample-app](https://github.com/SAP/openui5-sample-app)
2. npm install --save-dev serve-static
3. ui5 build -a
4. ui5 serve
    - Note page renders (as expected), add ?sap-ui-debug=true, everything still works
5. Fire up static server with this script (unzip and place in root of project):
[serve.zip](https://github.com/SAP/ui5-builder/files/2865111/serve.zip)
6. run server with ```node serve.js``` 
7. Observe the page loads as expected, again add the ?sap-ui-debug=true parameter.

## Context
- UI5 Module Version 1.1.0

## Affected components *(if known)*
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Likely reason for this issue
It appears that sap-ui-core-dbg.js believes its sap-ui-core.js and therefore calls for sap-ui-core-dbg.js to be loaded (and the loop goes on). I expected sap-ui-core-dbg.js to be a 1:1 copy of the original source of sap-ui-core.js, but its not. Its like its half backed.
Replacing the contents of sap-ui-core-dbg.js with the original source code of sap-ui-core.js resolves this issue.

**Comment by srenwickblum** [comment]
Correction to my earlier assessment...
sap-ui-core lists out (and loads) its set of dependencies using document.write(). For us this happens too late causing [violations ](https://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/) and failure to execute the script. 
![image](https://user-images.githubusercontent.com/36000044/52839140-4e486980-30f5-11e9-9c4b-c14ed6f27588.png)
The original source code in code sap-ui-core.js only works (when pasted into sap-ui-core-dbg.js) because its heavily relying on the fact it will be loaded as part of the document. We need to load your script dynamically, so running in debug mode this is no longer possible for us or anyone dynamically loading your scripts (since this move to npm and ui5-builder).
I experimented around with changing sap-ui-core.js to use the "document.createElement()" approach, instead of document.write(), but this require a good few changes, it introduces a lot of timing issues and a breaking change for users still using the sap.ui.getCore().attachInit()

Referring back to how things were done previously (the bower builds), the solution it seems, was to concatenate all of sap-ui-core.js's dependencies in-line inside sap-ui-core-dbg.js, thus avoiding the need to use the document.write() and requireSync. This approach would work for anyone who cannot statically place the openui5 start script directly onto the html page.

**Comment by matz3** [comment]
@srenwickblum thanks for reporting. This is fixed with [@ui5/cli v1.2.1](https://github.com/SAP/ui5-cli/releases/tag/v1.2.1).
