### ISSUE TITLE
[enhancement] Generate application preload

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [SAP/ui5-builder#279]
Correct me if I'm wrong but I understand that this node tooling is used to replace the legacy maven `ui5builder-maven-plugin`.
This plugin includes a goal `merge-modules` which helps to generate a big "application-preload" file which can be used to serve as a single download file for a complete application (including launchpad and utilities, for example)

I can't find any equivalent here in ui5-builder. I had a look across all tasks and even if I manage to generate component-preload, it seems there is no way of creating a unique application-preload.

Is it correct? Is this feature still a feature or is it planned to be retired/not ported to node ?

Thanks.
Guillaume

**Comment by matz3** [comment]
I think you are referring to the (here so called) [self-contained build](https://github.com/SAP/openui5-sample-app/#option-2-self-contained-build).
There is currently a default bundling available when e.g. running `ui5 build self-contained´ via the CLI.
A more detailed documentation about the bundler and its options are currently in-progress: https://github.com/SAP/ui5-builder/pull/219, https://github.com/SAP/ui5-project/pull/153

So most of the features which are still relevant have been ported to node as part of this project.
