### ISSUE TITLE
 .ui5ignore file as a tool to resolve what to build and what not || .gitignore / .npmignore support 

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/ui5-builder#352]
Hi, guys

I have a proposal. 

Sometimes it is convenient to control what to include and what not into build.

I am really afraid - that CLI option is not a right place to resolve this dependencies as this list might be quite complicated.

Working with git and npm we already have standard in using .gitignore and .npmignore files to control what is going to be pushed and published.

So it might be a nice feature also to have .ui5ignore file to control what is gonna be build.

For example I would like to define some dependency inside src folder ( lodash.merge or moment.js ) and I want to build library only with index.js file - ignoring the rest.

Thank you!

**Comment by RandomByte** [comment]
Hey @ThePlenkov,

Thank you for this suggestion.

Just checking, are you aware of the `builder.resources.excludes` ui5.yaml configuration (see [documentation](https://sap.github.io/ui5-tooling/pages/Configuration/#builder-optional))? I think this should already help with your use case.

**Comment by ThePlenkov** [comment]
@RandomByte - actually I haven’t seen it. Thank you. Gonna try it - may be is enough

**Comment by ThePlenkov** [comment]
yes, this section makes its work. Thank you! I will sync it manually with gitignore)) Thanks!
