### ISSUE TITLE
Preload building of Fiori element-based apps produce verbose log content

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-builder#404]
## Expected Behavior
Build is successful without error logging.

## Current Behavior
Build is logging a verbose error when analyzing the dependencies of apps using modules from Smart Templates / Fiori elements. 

## Steps to reproduce the issue
1.  Create a Fiori elements based app in SAP Web IDE
2. Run the build in SAP Web IDE or the ui5 build directly

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `latest`
- Node.js Version: `independent`
- npm Version: `independent`
- OS/Platform: `independent`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace

```
Running task generateComponentPreload...
ERR! lbt:analyzer:SmartTemplateAnalyzer Error: resource not found in pool: 'sap/suite/ui/generic/template/ListReport/Component.js'
ERR! lbt:analyzer:SmartTemplateAnalyzer     at LocatorResourcePool.findResource (/tmp/webide.668.build/proj/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/resources/ResourcePool.js:177:10)
```

**Comment by codeworrior** [comment]
Looks like the app is missing a mandatory dependency.

**Comment by petermuessig** [comment]
Yes, a dependency from the UI5 distribution layer which we need to publish. I just want to document this here to have a reference for customer tickets.

**Comment by ShashankPincha** [comment]
Facing the same issue, unfortunately raised a ticket in @ui5/cli before I saw this ticket. https://github.com/SAP/ui5-cli/issues/294

Is there any solution?

**Comment by petermuessig** [comment]
Hi @ShashankPincha , it is not a critical issue, just a logging that the SmartTemplate (Fiori elements) stuff is missing as a dependency and thus the builder logs this as missing modules. We are working right now to release the SAPUI5 dependencies on npmjs.com which will happen hopefully soon. The solution is in the pipeline... :-)

**Comment by ShashankPincha** [comment]
Hi @petermuessig.
Yup, I deployed to ABAP Repo and opened the app in the FLP and it all worked fine, I got the bellow error after deployment (not 100% sure if it's related) so I thought it maybe a critical issue.

![image](https://user-images.githubusercontent.com/50869295/73595175-ecb02380-452e-11ea-9e10-7f4d21866212.png)

Thank you.

**Comment by RandomByte** [comment]
The missing SAPUI5 dependency "sap.suite.ui.generic.template" is now available for install through the UI5 Tooling. See https://sap.github.io/ui5-tooling/pages/SAPUI5/ and https://blogs.sap.com/2020/04/01/ui5ers-buzz-49-the-ui5-tooling-and-sapui5-the-next-step/ for details

**Comment by RandomByte** [comment]
Reopening this issue based on new input. The error message reported here is not expected when generating a Component Preload.

@codeworrior and I already figured out a potential solution, PR will follow
