### ISSUE TITLE
Project Shims ignored by bundle configuration

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-builder#422]
## Expected Behavior
When configured, shims should be included in a build bundle.

## Current Behavior
It seems that project shims can not be included in bundles, even when such a [build configuration](https://github.com/BenReim/openui5-sample-app/blob/bundle-shims/ui5.yaml) exists.

## Steps to reproduce the issue
1. Clone and checkout minimal sample project
`git clone -b bundle-shims https://github.com/BenReim/openui5-sample-app.git`

2. Run build
`npm install && ui5 build --a`

3. Inspect `Component-preload.js`. It does not contain the moment library.

## Minimal Sample 
https://github.com/BenReim/openui5-sample-app/tree/bundle-shims

**Comment by RandomByte** [comment]
Hey, it seems that you need to make the following change in your ui5.yaml:
```patch
-        - "sap/ui/demo/todo/3rdparty/libs/moment-with-locales.min"
+        - "sap/ui/demo/todo/3rdparty/libs/moment-with-locales.min.js"
```

Opposing to the `sap.ui.require` syntax, here the file suffix always needs to be defined.
