### ISSUE TITLE
Builder Tasks List Documentation Missing

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-builder#446]
## Current Behavior
When following the tooling documentation and navigating to the task list, a 404 page is shown.

## Steps to reproduce the issue
1. Navigate to builder task section
https://sap.github.io/ui5-tooling/pages/Builder/#tasks
2. Click on "Available tasks are listed here."
3. 404 Page is shown

**Comment by RandomByte** [comment]
Bummer, I think we broke the JSDoc of all index.js

Thanks for reporting! We'll look into it. Anyways, we should also rework the Builder documentation page.

In the meantime, maybe the source can help you: https://github.com/SAP/ui5-builder/blob/master/index.js#L5

**Comment by RandomByte** [comment]
This has been resolved by @matz3 in one of the latest releases. Task documentation is now back: https://sap.github.io/ui5-tooling/api/module-@ui5_builder.tasks.html
