### ISSUE TITLE
sap-ui-cachebuster-info.json isn't generated for library project

### ISSUE THREAD

**Issue by ljheric** [SAP/ui5-builder#452]
## Expected Behavior
sap-ui-cachebuster-info.json should be generated for ui5 library project when the generateCachebusterInfo task is included in ui5 build command of package.json

## Current Behavior
sap-ui-cachebuster-info.json is not generated for ui5 library project when the generateCachebusterInfo task is included in ui5 build command of package.json

## Steps to reproduce the issue
1. Create a ui5 library project manually or web ide.
2. add option '--include-task=generateCachebusterInfo' in the ui5 build command in build script of package.json.
3. run 'npm run build-for-deploy'.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `2.0.3`
- Node.js Version: `v10.15.0`
- npm Version: `6.4.1`
- OS/Platform: `macOS 10.15.4`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by petermuessig** [comment]
Hi @ljheric,

for what purpose do you need the cachebuster information for libraries? This cachebuster information is only useful for UI5 applications. The UI5 framework is using the application cachebuster information to redirect the application resources but for libraries this information is never been used. Can you please elaborate a bit more on your use-case? 

THX and BR,
Peter

**Comment by RandomByte** [comment]
Closing due to lack of information from reporter.
