### ISSUE TITLE
How to Configure the UI5 Build into FLP?

### ISSUE THREAD

**Issue by LuisaG** [SAP/ui5-builder#478]
Dear colleagues, 

 

I am working on developing a SAPUI5 Fiori app for the Security Self Service team.

 

Application loading time and rendering of UI elements is quite slow, so we decided to uglify and minify the code. This is achieved with the help of @sap/ui5-builder-webide-extension, following the help.sap tutorial from [here](https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/96e7826ed3e747e6b0aac68699d92bfa.html).

 

The code is processed and placed - minified and uglified - into the dist folder, that resides directly under the root folder. However when we deploy the app to the Fiori Launchpad or try to run it as SAP Fiori Launchpad Sandbox, the code is read from the webapp folder, not from the dist.

 

We tried several approaches, but were not able to change the location from where the source code is loaded. How can we achieve this?

 

Thank you,

Luisa

**Comment by RandomByte** [comment]
Hi @LuisaG,

Apparently we are not familiar with this particular deployment process. Are you deploying from SAP Web IDE or locally? I think you should get in touch with the team responsible for the deployment step (e.g. Web IDE). It sounds like the UI5 Tooling correctly builds the project into the dist directory.

**Comment by LuisaG** [comment]
Hi @RandomByte,

Thank you for your feedback. I'm using WebIde for deployment, so I'll open a ticket on their side.
