### ISSUE TITLE
Issue with UI5 in Azure CI/CD Pipelines

### ISSUE THREAD

**Issue by mkkannan** [SAP/ui5-builder#522]
Using Azure CICD Pipeline it was working with grunt builder . Now it is not working anymore with the switch to custom/ui5cli.
We getting an error.

We are following the blog below.

https://blogs.sap.com/2019/10/24/how-to-use-project-piper-docker-images-for-cicd-with-azure-devops/comment-page-1/#comment-530613

ERROR: Failed to build module “Demo”. Builder not found: “custom”

 **mta.yaml**

 build-parameters:
      builder: custom
      commands:
        - npm install
        - npm run build
      supported-platforms: []
      build-result: dist

**Comment by svbender** [comment]
Hi, this issue doesn't seem to be UI5 tooling related. The provided yaml configuration belongs to the mta builder/tooling. The error message is also not from the UI5 tooling. Unfortunately we can not help you with the mta builder. If there is an issue with the UI5 tooling you may check the console output of the `ui5-cli` and provide this information together with further steps to reproduce it.
