### ISSUE TITLE
resourceListCreator: Do not throw for resources outside of a libraries namespace (a.k.a. "orphans")

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-builder#530]
## Expected Behavior
Like in our current Maven build, resources outside of a libraries namespace shall not fail the build. Instead, they should be ignored. This can be archived using the `failOnOrphans` configuration which currently defaults to true: https://github.com/SAP/ui5-builder/blob/master/lib/processors/resourceListCreator.js#L134

## Current Behavior

Resources outside of a libraries namespace which are not configured as ["externalResources"](https://github.com/SAP/ui5-builder/blob/master/lib/tasks/generateResourcesJson.js#L21) cause a build error `resources.json generation failed with error: There are <n> resources which could not be assigned to components.`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by tobiasso85** [comment]
Can be reproduced by:
cloning openui5
navigating to
`cd openui5/src/sap.ui.core`
creating file 
`touch src/sap/x.js`
running
`ui5 build --all --include-task=generateResourcesJson`

Error:
```bash
info builder:builder library sap.ui.core 🔨 (9/9) Running task generateResourcesJson...
ERR! builder:processors:resourceListCreator resources.json generation failed because of unassigned resources: sap/x.js, sap/x-dbg.js
ERR! builder:builder Build failed in 31 s
```
