### ISSUE TITLE
Error handling: Resource Component-preload.js has no content

### ISSUE THREAD

**Issue by TheGreenToaster** [SAP/ui5-builder#7]
## Expected Behavior
After running `ui5 init` the project should be able to build the project

## Current Behavior
After running `ui5 init` the build fails because there is no `metadata.namespace` property in the `ui5.yaml` file.

## Steps to reproduce the issue
1. clone an existing project
2. run `ui5 init`
3. run `ui5 build`
4. get error `Error: Resource Component-preload.js has no content`

## Context
- OS/Platform: Win10
- Node.js Version: 8.9.4
- npm Version: 5.8.0

## Affected components
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [x] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Resolution
Perhaps the namespace could be read from the `sap.app.id` in the `manifest.json` file if it exists. If it does not exist then output warning the user or even a prompt for input might be acceptable? Also in the build perhaps a check could be performed if the namespace field exists and throws a meaningful error in its absence.

**Comment by TheGreenToaster** [comment]
Also entered SAP/ui5-cli#3

**Comment by RandomByte** [comment]
+1. We already have a verbose log `"No manifest found for project ${project.metadata.name}. This might be an error in the future!"`. We definitely require a namespace for all applications, plus we'd like to enforce the presence of a `manifest.json` file for **new** apps.

So, to be compatible with existing apps, we could do the following:
1. Try to read namespace from `manifest.json`
2. Try to read namespace from `ui5.yaml` (`metadata.namespace`)

=> If unable to determine namespace, **throw error**
=> If a namespace is present in both sources, **throw error**

`manifest.json` should always be the preferred source, so the `ui5.yaml` option should go undocumented until more people complain that they don't want to add a `manifest.json` to their app.

**Comment by RandomByte** [comment]
In version 2.x of the UI5 Tooling we added additional checks and always require a project namespace now. Therefore closing this issue.
