### ISSUE TITLE
${version} is not replaced in manifest.json files

### ISSUE THREAD

**Issue by mauriciolauffer** [SAP/ui5-builder#76]
## Expected Behavior
When building my webapp, string "${version}" should be replace in manifest.json

## Current Behavior
ui5-builder creates a 

## Steps to reproduce the issue
1. Checkout the official sample app https://github.com/SAP/openui5-sample-app/tree/ui5-tooling
2. Edit manifest.json file to: 
  "sap.app": {
	"id": "sap.ui.demo.todo",
	"type": "application",
	"applicationVersion": {
	  "version": "${version}"
	}
  },

3. Run $ui5 build
4. Check the built version and open manifest.json file.

## Context
- OS/Platform: *
- Node.js Version: *
- npm Version: *
- Other information: ui5-builder v0.2.1

## Affected components
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
Pending release

**Comment by RandomByte** [comment]
This has been fixed with [ui5-builder release 0.2.3](https://github.com/SAP/ui5-builder/releases/tag/v0.2.3).

You can update a globally installed UI5 CLI to use the new version of UI5 Builder by executing `npm install --global @ui5/cli`. Please let us know if there are any issues.

**Comment by mauriciolauffer** [comment]
@RandomByte thanks for that... Just one more thing, you haven't published it to NPM. Latest version there is v0.2.1

https://www.npmjs.com/package/@ui5/cli

**Comment by RandomByte** [comment]
You're right, thanks. @ui5/cli v0.2.2 just got released: https://github.com/SAP/ui5-cli/releases/tag/v0.2.2
